### ISSUE TITLE
Roadmap to Version 1.0

### ISSUE THREAD

**Issue by mayer79** [mayer79/flashlight#53]
During the next months, "flashlight" will be revised with the following changes in mind:

- [x] Modern code formatting #54
- [x] `::` instead of `importFrom` #54
- [x] Replace `ggplot2::aes_string()` by `rlang::.Data` #54
- [x] Use linewidth aesthetic in `geom_line()` instead of size #54
- [x] Git actions
- [x] Shorter (and less) vignettes #54
- [x] Reduce package dependencies, e.g. {caret}, {xgboost}, {ranger}, {moderndive}, {mlr3}, {mlr3learners} #54
- [x] Flip x and y coordinates, and remove `coord_flip()` in `plot.light_breakdown()` and `plot.light_importance()` #57
- [x] Deprecate `add_shap()` in favour of {kernelshap} and {shapviz}. This will greatly simplify the code. The current implementation is too slow to be useful. #56
- [x] Deprecate `plot_counts()`. Might be replaced by {ggside} later, see below. Plus heavy dependency with {cowplot} #57
- [x] Deprecate `stats = "quartiles"` argument in profile functions. Too much code for too little gain. #57
- [x] Remove the unnecessarly complex configuration of special columns like "label", "metric" etc.  #57
- [x] Hide internal functions #56 #57 #58
- [x] Better examples #58
- [x] Replace `light_recode()` by `plot.light_effects(..., recode_labels = ....)` #60 
- [ ] Consider using nice default colors in the plots (e.g., via options()).
- [ ] Better interface to initialize and update flashlights and multiflashlights
- [ ] Consider using explicit argument lists in `light_*.multiflashlight()` functions in order to see type hints of RStudio
- [ ] Better unit tests

### Backlog

- [ ] Consider using the "collapse" package for grouped (weighted) averages, counts, medians.

```r
library(ggplot2)
library(ggside)

ggplot(iris, aes(Species, Sepal.Width)) + 
  geom_jitter(aes(color = Species)) + 
  geom_xsidebar(aes(fill=Species)) +
  geom_ysidehistogram(bins = 9) +
  theme_ggside_void()
```
<img width="275" alt="image" src="https://user-images.githubusercontent.com/16206095/228648993-7e379dba-9a58-4ec2-849a-d613540861c3.png">
